name: Release Build

# Trigger whenever you publish or update a release on GitHub:
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python: [3.12]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyinstaller pyautogui

      - name: Build with PyInstaller
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            pyinstaller \
              --windowed \
              --name "AutoTyper" \
              --icon icon.icns \
              writer.py
          else
            pyinstaller \
              --windowed \
              --onefile \
              --name "AutoTyper" \
              --icon icon.icns \
              writer.py
          fi

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          name: ${{ github.event.release.name }}
          body: ${{ github.event.release.body }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload built assets
        uses: actions/upload-release-asset@v2
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: |
            dist/AutoTyper.app
            dist/AutoTyper.exe
          asset_name: |
            AutoTyper-${{ matrix.os }}${{ matrix.os == 'macos-latest' && '.app' || '.exe' }}
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
