# .github/workflows/release-build.yml
name: Build & Upload Release Assets

on:
  release:
    types: [published]   # runs when you click “Publish release” in GitHub

jobs:
  build-and-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python: [3.12]

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pyinstaller pyautogui

    - name: Build AutoTyper
      run: |
        if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          pyinstaller --windowed \
            --name "AutoTyper" \
            --icon icon.icns \
            writer.py
          ARTIFACT_PATH="dist/AutoTyper.app"
          ARTIFACT_NAME="AutoTyper-macOS.app"
        else
          pyinstaller --windowed --onefile \
            --name "AutoTyper" \
            --icon icon.icns \
            writer.py
          ARTIFACT_PATH="dist/AutoTyper.exe"
          ARTIFACT_NAME="AutoTyper-Windows.exe"
        fi

    - name: Upload to GitHub Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ ARTIFACT_PATH }}
        asset_name: ${{ ARTIFACT_NAME }}
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
