# .github/workflows/release-build.yml
name: Build & Upload Release Assets

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  build-macos:
    name: macOS universal2
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install pyinstaller pyautogui pillow

      - name: Build universal2 .app
        run: |
          pyinstaller --windowed \
            --name "AutoTyper" \
            --icon icon.icns \
            --target-arch "arm64;x86_64" \
            writer.py
          cd dist
          zip -r AutoTyper-macOS-universal2.zip AutoTyper.app

      - name: Upload macOS asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url:        ${{ github.event.release.upload_url }}
          asset_path:        dist/AutoTyper-macOS-universal2.zip
          asset_name:        AutoTyper-macOS-universal2.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN:     ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install pyinstaller pyautogui pillow

      - name: Build .exe
        shell: bash
        run: |
          pyinstaller --windowed --onefile \
            --name "AutoTyper" \
            --icon icon.icns \
            writer.py

      - name: Upload Windows asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url:        ${{ github.event.release.upload_url }}
          asset_path:        dist/AutoTyper.exe
          asset_name:        AutoTyper-Windows.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN:     ${{ secrets.GITHUB_TOKEN }}
